# AUTOGENERATED! DO NOT EDIT! File to edit: datadownload.ipynb.

# %% auto 0
__all__ = ['MyTestClass', 'my_test_function']

# %% datadownload.ipynb 3
class MyTestClass:
    pass

def my_test_function():
    pass
