tasks:
  - source: pipeline/src/datadownload.py
    product:
      nb: pipeline/products/datadownload.ipynb
      data: pipeline/data/database/car_data.duckdb
  - source: pipeline/src/eda-pipeline.ipynb
    product: 
      nb: pipeline/products/eda-pipeline.ipynb